(()=>{'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');const el=id=>document.getElementById(id);const W=2200;let G=420;const DAY=540,NIGHT=240,CYCLE=DAY+NIGHT;const recipes={bed:{name:'침대',cost:{stone:3,metal:2,fiber:2},w:72,h:45,work:7},farm:{name:'농장',cost:{stone:2,fiber:5},w:96,h:30,work:6},wall:{name:'방벽',cost:{stone:6,metal:3},w:35,h:85,work:8}};
const initial=()=>({time:0,day:1,hp:100,food:4,inv:{stone:5,metal:2,fiber:3},player:{x:880,y:G-27},sites:[],allies:[],enemies:[],resources:[],kills:0});let s;try{s=JSON.parse(localStorage.getItem('alien-survival-save'))||initial()}catch{s=initial()}s.resources=s.resources||[];s.enemies=s.enemies||[];s.sites=s.sites||[];s.allies=s.allies||[];let tool='mine',speed=1,keys={},view=0,scale=1,logicalW=960,logicalH=540,last=performance.now(),spawnTick=0,actTick=0,attackTick=0,saveTick=0,toastTick=0,selectedAlly=0;
function rand(a,b){return a+Math.random()*(b-a)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function toast(t){el('toast').textContent=t;el('toast').classList.add('show');toastTick=3}function save(){localStorage.setItem('alien-survival-save',JSON.stringify(s));toast('진행 상황을 저장했어요')}
function addResource(){let x=rand(95,W-95),types=['stone','stone','fiber','fiber','metal','food'];s.resources.push({x,type:types[Math.floor(rand(0,types.length))],hp:2})}while(s.resources.length<32)addResource();
function resize(){let d=Math.min(devicePixelRatio||1,2),portrait=innerHeight>innerWidth;canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';logicalH=portrait?780:Math.round(960*innerHeight/innerWidth);logicalW=portrait?Math.round(780*innerWidth/innerHeight):960;G=Math.round(logicalH*(portrait?.57:.78));scale=canvas.width/logicalW;ctx.setTransform(scale,0,0,scale,0,0);ctx.imageSmoothingEnabled=false}window.addEventListener('resize',resize);resize();
const phase=()=>s.time%CYCLE<DAY?'낮':'밤',remaining=()=>phase()==='낮'?DAY-s.time%CYCLE:CYCLE-s.time%CYCLE;function near(x,d=72){return Math.abs(s.player.x-x)<d}function totalCost(r){return Object.entries(r.cost).map(([k,v])=>`${label(k)} ${v}`).join(' · ')}function label(k){return {stone:'광석',metal:'금속',fiber:'섬유',food:'식량'}[k]}
function act(){let r=s.resources.filter(a=>near(a.x,62)).sort((a,b)=>Math.abs(a.x-s.player.x)-Math.abs(b.x-s.player.x))[0];let site=s.sites.filter(a=>!a.done&&near(a.x,100)).sort((a,b)=>Math.abs(a.x-s.player.x)-Math.abs(b.x-s.player.x))[0];if(site&&(!r||Math.abs(site.x-s.player.x)<Math.abs(r.x-s.player.x))){deliver(site,true);return}if(r){r.hp--;let gain=r.type;if(gain==='food')s.food++;else s.inv[gain]++;toast(`${label(gain)} +1`);if(r.hp<=0){s.resources.splice(s.resources.indexOf(r),1);setTimeout(addResource,2500)}return}toast('자원이나 건설 현장 가까이 이동하세요')}
function deliver(site,player){let recipe=recipes[site.kind],delivered=false;for(const [k,v] of Object.entries(recipe.cost)){let need=v-(site.put[k]||0),n=Math.min(need,s.inv[k]||0,player?99:1);if(n>0){s.inv[k]-=n;site.put[k]=(site.put[k]||0)+n;delivered=true;if(!player)break}}if(delivered)toast(`${recipe.name}에 재료를 넣었어요`);else if(player)toast('필요한 재료가 부족하거나 이미 채웠어요')}
function supplied(site){return Object.entries(recipes[site.kind].cost).every(([k,v])=>(site.put[k]||0)>=v)}function build(x,kind){let r=recipes[kind];x=clamp(x,70,W-70);if(s.sites.some(a=>Math.abs(a.x-x)<(recipes[a.kind].w+r.w)/2+12)){toast('다른 건물과 너무 가까워요');return}if(Math.abs(x-s.player.x)>310){toast('플레이어 가까이에 설계도를 놓으세요');return}s.sites.push({x,kind,put:{},progress:0,done:false});toast(`${r.name} 설계도 설치! 재료를 운반하세요`);tool='mine';renderButtons()}
function recruit(){let beds=s.sites.filter(a=>a.done&&a.kind==='bed').length;if(s.allies.length>=beds){toast('완성된 빈 침대가 필요해요');return}if(s.food<2){toast('동료 모집에는 식량 2개가 필요해요');return}s.food-=2;s.allies.push({x:s.player.x+40,role:'haul',hp:50,work:0});toast('구조 신호에 동료가 합류했어요!')}
function assign(){if(!s.allies.length){toast('먼저 침대와 식량으로 동료를 모집하세요');return}selectedAlly%=s.allies.length;const a=s.allies[selectedAlly];let roles=['haul','gather','guard'];a.role=roles[(roles.indexOf(a.role)+1)%3];toast(`${selectedAlly+1}번 동료: ${roleName(a.role)} (다시 누르면 변경)`)}function roleName(r){return {haul:'운반·건설',gather:'채집',guard:'경비'}[r]}
function damageEnemy(e,d){e.hp-=d;if(e.hp<=0){s.enemies.splice(s.enemies.indexOf(e),1);s.kills++;if(Math.random()<.35){s.food++;toast('외계 생물에서 식량 +1')}}}function attack(){let e=s.enemies.filter(a=>Math.abs(a.x-s.player.x)<85).sort((a,b)=>Math.abs(a.x-s.player.x)-Math.abs(b.x-s.player.x))[0];if(e)damageEnemy(e,18);else toast('공격 범위에 적이 없어요')}
function resetAfterDeath(){s.hp=100;s.food=Math.max(1,s.food-2);s.player.x=880;s.enemies=[];s.time=Math.floor(s.time/CYCLE)*CYCLE+90;toast('쓰러졌어요. 식량 2개를 잃고 기지에서 회복했어요')}
function update(dt){let step=Math.min(dt,.05)*speed,safe=phase();let move=(keys.right?1:0)-(keys.left?1:0);s.player.x=clamp(s.player.x+move*170*dt,20,W-20);if(keys.act){actTick-=dt;if(actTick<=0){act();actTick=.42}}else actTick=0;if(keys.attack){attackTick-=dt;if(attackTick<=0){attack();attackTick=.38}}else attackTick=0;
let prev=Math.floor(s.time/CYCLE);s.time+=step;if(Math.floor(s.time/CYCLE)>prev){s.day++;s.food=Math.max(0,s.food-Math.max(1,Math.ceil(s.allies.length/2)));for(let a of s.sites)if(a.done&&a.kind==='farm')s.food+=3;toast(`새로운 낮! 식량 소비 후 농장 수확 · ${s.day}일차`)}
if(s.time%CYCLE>=DAY){spawnTick-=step;if(spawnTick<=0){spawnTick=clamp(13-s.day*.7,3,13);let x=Math.random()<.5?clamp(s.player.x-rand(430,650),25,W-25):clamp(s.player.x+rand(430,650),25,W-25);s.enemies.push({x,hp:26+s.day*4,strike:0})}}else spawnTick=0;
for(let site of s.sites){if(site.done||!supplied(site))continue;let workers=s.allies.filter(a=>a.role==='haul'&&Math.abs(a.x-site.x)<80).length;site.progress+=step*(near(site.x,105)?1:0)+step*workers*.75;if(site.progress>=recipes[site.kind].work){site.done=true;toast(`${recipes[site.kind].name} 완성!`)}}
for(let a of s.allies){a.work=(a.work||0)-step;let target=s.player.x;if(a.role==='haul'){let site=s.sites.find(v=>!v.done);if(site)target=site.x-18;else target=880;if(site&&Math.abs(a.x-site.x)<65&&a.work<=0&&!supplied(site)){deliver(site,false);a.work=2.2}}else if(a.role==='gather'&&safe==='낮'){let r=s.resources.filter(v=>Math.abs(v.x-a.x)<280).sort((u,v)=>Math.abs(u.x-a.x)-Math.abs(v.x-a.x))[0];if(r){target=r.x;if(Math.abs(a.x-r.x)<32&&a.work<=0){if(r.type==='food')s.food++;else s.inv[r.type]++;r.hp--;if(r.hp<=0){s.resources.splice(s.resources.indexOf(r),1);setTimeout(addResource,2400)}a.work=5}}}else if(a.role==='guard')target=880+((s.allies.indexOf(a)%3)-1)*70;if(Math.abs(target-a.x)>9)a.x+=Math.sign(target-a.x)*Math.min(Math.abs(target-a.x),80*step);let enemy=s.enemies.find(e=>Math.abs(e.x-a.x)<85);if(enemy&&a.work<=0){damageEnemy(enemy,12);a.work=.9}}
for(let e of [...s.enemies]){e.strike-=step;let wall=s.sites.find(a=>a.done&&a.kind==='wall'&&Math.abs(a.x-e.x)<34);let target=wall?wall.x:s.player.x;e.x+=Math.sign(target-e.x)*clamp(39+s.day*2,40,90)*step;if(Math.abs(e.x-s.player.x)<26&&e.strike<=0){s.hp-=10;e.strike=1.2;if(s.hp<=0)resetAfterDeath()}if(!wall){let farm=s.sites.find(a=>a.done&&a.kind==='farm'&&Math.abs(a.x-e.x)<35);if(farm&&e.strike<=0){farm.done=false;farm.put={};farm.progress=0;e.strike=3;toast('농장이 공격받아 다시 지어야 해요')}}}
if(s.resources.length<25&&Math.random()<step*.15)addResource();saveTick+=dt;if(saveTick>15){localStorage.setItem('alien-survival-save',JSON.stringify(s));saveTick=0}if(toastTick>0){toastTick-=dt;if(toastTick<=0)el('toast').classList.remove('show')}view=clamp(s.player.x-logicalW*.5,0,W-logicalW);}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function text(t,x,y,color='#fff',size=13){ctx.fillStyle=color;ctx.font=`bold ${size}px monospace`;ctx.fillText(t,Math.round(x),Math.round(y))}function draw(){let night=phase()==='밤';let h=logicalH;let sky=ctx.createLinearGradient(0,0,0,G);sky.addColorStop(0,night?'#111330':'#213f62');sky.addColorStop(1,night?'#3d3157':'#8a7482');ctx.fillStyle=sky;ctx.fillRect(0,0,logicalW,h);ctx.save();ctx.translate(-view,0);
for(let i=0;i<85;i++){let x=((i*379+73)%W),y=16+(i*73)%250;rect(x,y,i%7===0?3:2,2,night?'#cad9eb':'#9db9c5')}
for(let i=0;i<28;i++){let x=i*94+((i*173)%31);rect(x,G-100-(i%4)*14,44,G,'#3b4862');rect(x+8,G-117-(i%4)*14,23,19,'#9f8bac')}
rect(0,G,W,h-G,'#283546');rect(0,G,W,12,'#779d89');rect(0,G+12,W,8,'#496a6d');for(let i=0;i<160;i++){let x=(i*191)%W,y=G+28+(i*67)%Math.max(40,h-G-40);rect(x,y,5+(i%3)*3,3,i%3?'#4b5972':'#647b86')}
for(let r of s.resources){let x=r.x;if(r.type==='food'){rect(x-3,G-22,6,22,'#5a795c');rect(x-11,G-29,22,13,'#639f70');rect(x-8,G-25,5,5,'#ef8996');rect(x+4,G-23,5,5,'#ef8996')}else if(r.type==='fiber'){rect(x-3,G-21,6,21,'#487f6b');rect(x-10,G-25,19,9,'#a2ddaa');rect(x+2,G-36,7,13,'#7cbfa1')}else{rect(x-13,G-19,26,19,r.type==='metal'?'#8ca9c5':'#6e8495');rect(x-6,G-28,13,10,r.type==='metal'?'#9be8e6':'#9c8db8');rect(x+2,G-11,5,5,'#c8dae3')}}
for(let a of s.sites){let r=recipes[a.kind],x=a.x-r.w/2,y=G-r.h;if(!a.done){ctx.globalAlpha=.5;rect(x,y,r.w,r.h,'#7be6eb');ctx.globalAlpha=1;ctx.strokeStyle='#baf7ec';ctx.setLineDash([5,4]);ctx.strokeRect(x,y,r.w,r.h);ctx.setLineDash([]);let count=Object.entries(r.cost).reduce((n,[k,v])=>n+Math.min(v,a.put[k]||0),0),all=Object.values(r.cost).reduce((u,v)=>u+v,0);rect(x,y-12,r.w,5,'#17283c');rect(x,y-12,r.w*(count/all),5,'#e7c875');text(`${r.name} ${count}/${all}`,x,y-18,'#edf9f4',11)}else if(a.kind==='bed'){rect(x,y+16,r.w,r.h-16,'#586d80');rect(x+4,y+9,r.w-8,18,'#c7a987');rect(x+5,y+11,16,10,'#d7e1d8');rect(x,y+41,r.w,4,'#352c47')}else if(a.kind==='farm'){rect(x,y+17,r.w,13,'#684e52');for(let j=0;j<6;j++){rect(x+j*16+5,y+4,4,15,'#65bb85');rect(x+j*16+2,y,10,6,'#b2db85')}}else{rect(x,y,r.w,r.h,'#67808f');for(let j=0;j<4;j++)rect(x+3+j%2*15,y+4+Math.floor(j/2)*30,11,20,'#8aabaf')}}
for(let a of s.allies){rect(a.x-8,G-30,16,28,'#d2a681');rect(a.x-7,G-34,14,8,'#91d4ca');rect(a.x-5,G-25,10,5,'#2b3951');text(a.role==='haul'?'▣':a.role==='gather'?'✦':'⚔',a.x-6,G-43,'#dff5e6',13)}
for(let e of s.enemies){rect(e.x-12,G-24,24,24,'#a65885');rect(e.x-7,G-29,14,12,'#ba6b9b');rect(e.x-7,G-19,4,4,'#f2d6a4');rect(e.x+4,G-19,4,4,'#f2d6a4');rect(e.x-13,G-37,26,3,'#321c36');rect(e.x-13,G-37,26*e.hp/(26+s.day*4),3,'#e87990')}
let p=s.player;rect(p.x-9,G-29,18,28,'#e3b895');rect(p.x-10,G-36,20,12,'#e8d4ae');rect(p.x-8,G-25,16,8,'#407b91');rect(p.x-5,G-20,10,4,'#1c364a');rect(p.x-13,G-5,10,5,'#283246');rect(p.x+3,G-5,10,5,'#283246');ctx.restore();if(night){rect(0,0,logicalW,h,'#11092736');let glow=ctx.createRadialGradient(logicalW/2,G-30,10,logicalW/2,G-30,260);glow.addColorStop(0,'#e6c39620');glow.addColorStop(1,'#00000000');ctx.fillStyle=glow;ctx.fillRect(0,0,logicalW,h)}rect(0,G+12,logicalW,3,night?'#755a84':'#98ac9d');}
function hud(){let rem=remaining(),m=Math.floor(rem/60),sec=Math.floor(rem%60);el('clock').textContent=`${phase()==='낮'?'☀ 낮':'☾ 밤'} · ${s.day}일차  ${m}:${String(sec).padStart(2,'0')}  ♥ ${Math.max(0,Math.ceil(s.hp))}`;el('inv').textContent=`광석 ${s.inv.stone}  금속 ${s.inv.metal}  섬유 ${s.inv.fiber}  식량 ${s.food}  동료 ${s.allies.length}`;let nearby=s.sites.find(a=>!a.done&&near(a.x,110));el('status').textContent=nearby?`${recipes[nearby.kind].name}: ${Object.entries(recipes[nearby.kind].cost).map(([k,v])=>`${label(k)} ${nearby.put[k]||0}/${v}`).join(' · ')} · E로 넣기`:tool==='mine'?'자원에 가까이 가서 E 또는 ⛏':`${recipes[tool].name} 놓을 땅을 클릭`;}
function renderButtons(){document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool))}document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{let t=b.dataset.tool;if(recipes[t]){tool=t;toast(`${recipes[t].name} 필요: ${totalCost(recipes[t])}`)}else if(t==='mine')tool=t;else if(t==='recruit')recruit();else if(t==='assign')assign();else if(t==='save')save();renderButtons()}));renderButtons();el('speed').onclick=()=>{speed=speed===1?10:1;el('speed').textContent=`시간 ×${speed}`;toast(speed===10?'시간을 10배로 빨리 진행합니다':'보통 속도로 돌아왔어요')};document.querySelectorAll('#touch button').forEach(b=>{let k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[k]=true});for(let type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys[k]=false)});window.addEventListener('keydown',e=>{if(['a','ArrowLeft'].includes(e.key))keys.left=true;if(['d','ArrowRight'].includes(e.key))keys.right=true;if(e.key.toLowerCase()==='e')keys.act=true;if(e.key.toLowerCase()==='f')keys.attack=true});window.addEventListener('keyup',e=>{if(['a','ArrowLeft'].includes(e.key))keys.left=false;if(['d','ArrowRight'].includes(e.key))keys.right=false;if(e.key.toLowerCase()==='e')keys.act=false;if(e.key.toLowerCase()==='f')keys.attack=false});canvas.addEventListener('pointerdown',e=>{if(!recipes[tool])return;let x=(e.clientX*canvas.width/innerWidth)/scale+view;build(x,tool)});
function loop(now){let dt=(now-last)/1000;last=now;update(Math.min(dt,.1));ctx.setTransform(scale,0,0,scale,0,0);draw();hud();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
